#!/usr/bin/env bash
set -E -e -o pipefail

# Add repo specific metadata here.

BASE_IMAGE_CONFIG_KEY_PREFIX="BASE_IMAGE"

RELEASE_PACKAGE_NAME="Scrutiny"
RELEASE_TAG_PACKAGE_NAME="scrutiny"

UPSTREAM_PACKAGE_NAME="Scrutiny"
UPSTREAM_VERSION_CONFIG_KEY="SCRUTINY_VERSION"
UPSTREAM_GIT_REPO="https://github.com/AnalogJ/scrutiny"
GIT_REPO_TAGS_CUSTOM_FILTERING_REGEX='^v.+\-rc.+$'

TEST_TYPE="foreground"
TEST_CONTAINER_TYPE="scrutiny"

current_upstream_version() {
    get_config_arg ${UPSTREAM_VERSION_CONFIG_KEY:?}
}

latest_upstream_version() {
    git_remote_repo_latest_tag "${UPSTREAM_GIT_REPO:?}"
}

update_latest_upstream_version() {
    local cur_ver="${1:?}"
    local latest_ver="${2:?}"
    echo "Updating ${UPSTREAM_PACKAGE_NAME:?} ${UPSTREAM_VERSION_CONFIG_KEY:?} '${cur_ver:?}' -> '${latest_ver:?}'"
    set_config_arg "${UPSTREAM_VERSION_CONFIG_KEY:?}" "${latest_ver:?}"
    git add ${ARGS_FILE:?}
}

package_current_release_version() {
    current_upstream_version
}

test_start_container() {
    local container_name="${1:?}"
    docker run \
        --name ${container_name:?} \
        --rm \
        ${IMAGE:?} \
        scrutiny-web --version
    docker run \
        --name ${container_name:?} \
        --rm \
        ${IMAGE:?} \
        scrutiny-collector --version
}
